spring.application.name=consuming-rest
apiKey=''
apiUrl=https://api.openweathermap.org/data/2.5
spring.security.user.name=minnieMouse
spring.security.user.password=password123
spring.thymeleaf.cache=false